---

Paths:
  - 'app/*/**.rb'
  - 'lib/**.rb'
  - 'spec/**.rb'
Dictionaries:
  EnglishDictionaryFromGem:
    type: 'hunspell'
    language: 'en_US'
  DevelopmentDictionary:
    type: 'word_list'
    word_list:
      - json
      - params
      - html
      - url
      - unprocessable
      - ok
      - deserialization
