---

Paths:
  - 'app/*/**.rb'
  - 'lib/**.rb'
  - 'spec/**.rb'
Dictionaries:
  EnglishDictionaryFromGem:
    type: 'hunspell'
    language: 'en_US'
  DevelopmentDictionary:
    type: 'word_list'
    word_list:
      - json
      - params
      - html
      - url
      - unprocessable
      - ok
      - deserialization
      - dom
      - ul
      - li
      - br
      - railsban
      - kanban
      - doctype
      - viewport
      - CSRF
      - CSP
      - stylesheet
      - javascript
      - importmap
      - doctype
      - http
      - charset
      - utf
      - gemfile
      - ve
      - bundler
      - railties
      - canada
      - bootsnap
      - dev
      - tmp
      - txt
      - deprecations
      - uncomment
      - decrypt
      - apache
      - nginx
      - css
      - preprocessor
      - precompiled
      - stylesheets
      - http
      - sendfile
      - accel
      - wss
      - ssl
      - pii
      - prepend
      - mem
      - backend
      - resque
      - fallbacks
      - lookups
      - pid
      - syslog
      - stdout
      - isn
      - CI
      - stderr
      - npm
      - preload
      - hotwired
      - JS
      - precompile
      - https
      - rubyonrails
      - src
      - img
      - URI
      - nonces
      - passw
      - otp
      - ssn
      - inflector
      - tful
      - usb
      - fullscreen
      - pidfile
      - pids
      - DSL
      - luke
      - webdrivers
      - chromedriver
      - args
      - backgrounding
      - breakpad
      - shm
      - IPC
      - rendered
      - srgb
      - scrollbars
      - boolean
      - href
      - parallelize
      - renderer
      - YAML
      - UAT
      - cancelled
