---
inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  UseCache: true
  SuggestExtensions: true
  EnabledByDefault: true
  ActiveSupportExtensionsEnabled: true
  TargetRubyVersion: 3.1.2
  TargetRailsVersion: 7.0.4.2

require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rake
  - rubocop-thread_safety
  - rubocop-i18n
  - rubocop-require_tools

Layout/LineLength:
  Enabled: true
  Max: 122

Style/Copyright:
  Enabled: false
  AutocorrectNotice: ''

Style/Documentation:
  Enabled: false

Style/RequireOrder:
  Enabled: true
  Exclude:
    - 'config/boot.rb'

Style/MissingElse:
  Enabled: false

Style/DocumentationMethod:
  Enabled: true
  Exclude:
    - 'db/migrate/*.rb'

Require/MissingRequireStatement:
  Enabled: false

Rails/SchemaComment:
  Enabled: false

I18n/GetText/DecorateString:
  Enabled: true
  Exclude:
    - 'test/**/*_test.rb'

I18n/RailsI18n/DecorateString:
  Enabled: true
  Exclude:
    - 'test/**/*_test.rb'

Lint/ConstantResolution:
  Enabled: false

Layout/RedundantLineBreak:
  Enabled: true
  Exclude:
    - 'config/environments/*.rb'
    - 'config/initializers/*.rb'

Bundler/GemComment:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false
